name: Update GitHub Metrics SVG

on:
  schedule:
    - cron: "0 0 * * *"  # 每天 UTC 00:00 自動更新
  workflow_dispatch:        # 允許手動觸發

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: idontwannarock
          template: classic
          base: header, activity, community, repositories
          base_indepth: yes
          config_theme: dark
          config_display: large
          config_animations: no
          filename: github-metrics.svg
